name: 24/7 Kick Subscriber Counter Stream
on:
  push:
    branches: [ main ]
  workflow_dispatch: # يتيح لك زر التشغيل اليدوي للتجربة فوراً

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Google Chrome and FFmpeg
      run: |
        sudo apt-get update
        # تثبيت متصفح كروم الرسمي الكامل بدلاً من كروميوم لحل مشاكل المواقع
        wget https://google.com
        sudo apt install ./google-chrome-stable_current_amd64.deb -y
        sudo apt-get install -y ffmpeg xvfb

    - name: Start Virtual Screen and Stream to Kick
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        sleep 3
        # تشغيل كروم الرسمي في وضع ملء الشاشة مع تخطي الأمان للسيرفر
        google-chrome --no-sandbox --disable-gpu --window-size=1920,1080 --kiosk "sk_us-west-2_IOeLOk4jS3v9_EXRcvLHgKYwa9jdGu7x7eFGasrl0qr" &
        sleep 8
        # إرسال البث مع تفعيل بروتوكول الـ rtmps الآمن وتثبيت جودة معينة تناسب كيك
        ffmpeg -f x11grab -video_size 1920x1080 -i :99.0 -c:v libx264 -b:v 3000k -preset veryfast -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 -f flv "rtmps://://kick.com{{ secrets.KICK_STREAM_KEY }}"
