name: 24/7 Kick Subscriber Counter Stream
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install FFmpeg and Virtual Screen
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xvfb chromium-browser

    - name: Start Virtual Screen and Stream to Kick
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        sleep 3
        # تم وضع رابط عداد أبو فلة الصحيح والخفيف هنا بالأسفل
        chromium-browser --no-sandbox --disable-setuid-sandbox --disable-gpu --window-size=1920,1080 --kiosk "https://livecounts.io/youtube-live-subscriber-counter/UCqq5n-Oe-r1EEHI3yvhVJcA" &
        sleep 8
        # تم إصلاح رابط الإرسال الرسمي لكيك واستدعاء المفتاح السري الآمن بشكل برمي سليم
        ffmpeg -f x11grab -video_size 1920x1080 -i :99.0 -c:v libx264 -b:v 2500k -preset veryfast -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 -f flv "rtmps://://kick.com{{ secrets.KICK_STREAM_KEY }}"
